src/chapter6/beans/Comment.java
package chapter6.beans;

import java.io.Serializable;
import java.util.Date;

public class Comment implements Serializable {

    private int id;
    private int userId;
    private int messageId;
    private String text;
    private Date createdDate;
    private Date updatedDate;

    public int getId() {
    	return id;
    }
    public void setId(int id) {
    	this.id = id;
    }

    public int getUserId() {
    	return userId;
    }
    public void setUserId(int userId) {
    	this.userId = userId;
    }

    public int getMessageId() {
    	return messageId;
    }
    public void setMessageId(int messageId) {
    	this.messageId = messageId;
    }

    public String getText() {
    	return text;
    }
    public void setText(String text) {
    	this.text = text;
    }

    //改行コード
    public String[] getSplitedText() {
    	return text.split("\n");
    }

    public Date getCreatedDate() {
    	return createdDate;
    }
    public void setCreatedDate(Date createdDate) {
    	this.createdDate = createdDate;
    }

    public Date getUpdatedDate() {
    	return updatedDate;
    }
    public void setUpdatedDate(Date updatedDate) {
    	this.updatedDate = updatedDate;
    }

}

src/chapter6/controller/EditServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import chapter6.beans.Message;
import chapter6.service.MessageService;

@WebServlet(urlPatterns = { "/edit" })
public class EditServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

    	HttpSession session = request.getSession();
        String id = request.getParameter("id");
        Message message = null;
        List<String> errorMessages = new ArrayList<String>();

        if((!StringUtils.isBlank(id)) && id.matches("^[0-9]+$")) {
        	int messageId = Integer.parseInt(id);
        	message = new MessageService().select(messageId);
        }

        if(message == null) {
            errorMessages.add("不正なパラメータが入力されました");
            session.setAttribute("errorMessages", errorMessages);
            response.sendRedirect("./");
            return;
        }

    	request.setAttribute("message", message);
        request.getRequestDispatcher("edit.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

        HttpSession session = request.getSession();
        List<String> errorMessages = new ArrayList<String>();

        //IDが取得できていないnullでエラー
        String text = request.getParameter("text");
        String id = request.getParameter("id");
        int messageId = Integer.parseInt(id);


        if (!isValid(text, errorMessages)) {
            session.setAttribute("errorMessages", errorMessages);
            Message message = new MessageService().select(messageId);
            request.setAttribute("message", message);
            request.getRequestDispatcher("edit.jsp").forward(request, response);
            return;
        }

        Message message = new Message();
        message.setText(text);
        message.setId(messageId);

        new MessageService().update(message);
        response.sendRedirect("./");
    }

    private boolean isValid(String text, List<String> errorMessages) {

        if (StringUtils.isBlank(text)) {
            errorMessages.add("メッセージを入力してください");
        } else if (140 < text.length()) {
            errorMessages.add("140文字以下で入力してください");
        }

        if (errorMessages.size() != 0) {
            return false;
        }
        return true;
    }
}

src/chapter6/controller/LoginServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import chapter6.beans.User;
import chapter6.service.UserService;

@WebServlet(urlPatterns = { "/login" })
public class LoginServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

        request.getRequestDispatcher("login.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

        String accountOrEmail = request.getParameter("accountOrEmail");
        String password = request.getParameter("password");

        User user = new UserService().select(accountOrEmail, password);
        if (user == null) {
            List<String> errorMessages = new ArrayList<String>();
            errorMessages.add("ログインに失敗しました");
            request.setAttribute("errorMessages", errorMessages);
            request.getRequestDispatcher("login.jsp").forward(request, response);
            return;
        }

        HttpSession session = request.getSession();
        session.setAttribute("loginUser", user);
        response.sendRedirect("./");
    }
}

src/chapter6/controller/SettingServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import chapter6.beans.User;
import chapter6.exception.NoRowsUpdatedRuntimeException;
import chapter6.service.UserService;

@WebServlet(urlPatterns = { "/setting" })
public class SettingServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        HttpSession session = request.getSession();
        User loginUser = (User) session.getAttribute("loginUser");

        User user = new UserService().select(loginUser.getId());

        request.setAttribute("user", user);
        request.getRequestDispatcher("setting.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        HttpSession session = request.getSession();
        List<String> errorMessages = new ArrayList<String>();

        User user = getUser(request);


        if (isValid(user, errorMessages)) {
            try {
                new UserService().update(user);
            } catch (NoRowsUpdatedRuntimeException e) {
                errorMessages.add("他の人によって更新されています。最新のデータを表示しました。データを確認してください。");
            }
        }

        if (errorMessages.size() != 0) {
            request.setAttribute("errorMessages", errorMessages);
            request.setAttribute("user", user);
            request.getRequestDispatcher("setting.jsp").forward(request, response);
            return;
        }

        session.setAttribute("loginUser", user);
        response.sendRedirect("./");
    }

    private User getUser(HttpServletRequest request) throws IOException, ServletException {

        User user = new User();
        user.setId(Integer.parseInt(request.getParameter("id")));
        user.setName(request.getParameter("name"));
        user.setAccount(request.getParameter("account"));
        user.setPassword(request.getParameter("password"));
        user.setEmail(request.getParameter("email"));
        user.setDescription(request.getParameter("description"));
        return user;
    }

    private boolean isValid(User user, List<String> errorMessages) {

        String name = user.getName();
        String account = user.getAccount();
        String email = user.getEmail();
        Integer id = user.getId();

    	//アカウント重複判定
       	User accounts = new UserService().select(account);

       	if(accounts != null && id != accounts.getId()) {
            errorMessages.add("すでに存在するアカウントです");
       	}
        if (!StringUtils.isEmpty(name) && (20 < name.length())) {
            errorMessages.add("名前は20文字以下で入力してください");
        }
        if (StringUtils.isEmpty(account)) {
            errorMessages.add("アカウント名を入力してください");
        } else if (20 < account.length()) {
            errorMessages.add("アカウント名は20文字以下で入力してください");
        }
        if (!StringUtils.isEmpty(email) && (50 < email.length())) {
            errorMessages.add("メールアドレスは50文字以下で入力してください");
        }

        if (errorMessages.size() != 0) {
            return false;
        }
        return true;
    }
}

src/chapter6/controller/SignUpServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang.StringUtils;

import chapter6.beans.User;
import chapter6.service.UserService;

@WebServlet(urlPatterns = { "/signup" })
public class SignUpServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

        request.getRequestDispatcher("signup.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

        List<String> errorMessages = new ArrayList<String>();

        User user = getUser(request);

        if (!isValid(user, errorMessages)) {
            request.setAttribute("errorMessages", errorMessages);
            request.getRequestDispatcher("signup.jsp").forward(request, response);
            return;
        }
        new UserService().insert(user);
        response.sendRedirect("./");
    }

    private User getUser(HttpServletRequest request) throws IOException, ServletException {

        User user = new User();
        user.setName(request.getParameter("name"));
        user.setAccount(request.getParameter("account"));
        user.setPassword(request.getParameter("password"));
        user.setEmail(request.getParameter("email"));
        user.setDescription(request.getParameter("description"));
        return user;
    }

    private boolean isValid(User user, List<String> errorMessages) {

    	String name = user.getName();
        String account = user.getAccount();
        String password = user.getPassword();
        String email = user.getEmail();

    	//アカウント重複判定
       	User accounts = new UserService().select(account);
       	if(accounts != null) {
            errorMessages.add("すでに存在するアカウントです");
       	}

        if (!StringUtils.isEmpty(name) && (20 < name.length())) {
            errorMessages.add("名前は20文字以下で入力してください");
        }

        if (StringUtils.isEmpty(account)) {
            errorMessages.add("アカウント名を入力してください");
        } else if (20 < account.length()) {
            errorMessages.add("アカウント名は20文字以下で入力してください");
        }

        if (StringUtils.isEmpty(password)) {
            errorMessages.add("パスワードを入力してください");
        }

        if (!StringUtils.isEmpty(email) && (50 < email.length())) {
            errorMessages.add("メールアドレスは50文字以下で入力してください");
        }

        if (errorMessages.size() != 0) {
            return false;
        }
        return true;
    }
}

src/chapter6/controller/TopServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import chapter6.beans.User;
import chapter6.beans.UserComment;
import chapter6.beans.UserMessage;
import chapter6.service.CommentService;
import chapter6.service.MessageService;

@WebServlet(urlPatterns = { "/index.jsp" })
public class TopServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

        boolean isShowMessageForm = false;
        User user = (User) request.getSession().getAttribute("loginUser");
        String userId = request.getParameter("user_id");
        //選択した日付を取得
        String start = request.getParameter("start");
        String end = request.getParameter("end");

        if (user != null) {
            isShowMessageForm = true;
        }

        List<UserMessage> messages = new MessageService().select(userId, start, end);

        //コメント情報を取得してtop.jspに渡す
        List<UserComment> comments = new CommentService().select();


        request.setAttribute("messages", messages);
        request.setAttribute("start", start);
        request.setAttribute("end", end);
        request.setAttribute("comments", comments);
        request.setAttribute("isShowMessageForm", isShowMessageForm);
        request.getRequestDispatcher("/top.jsp").forward(request, response);
    }
}

WebContent/edit.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>つぶやきの編集</title>
        <link href="./css/style.css" rel="stylesheet" type="text/css">
    </head>

    <body>
	<div class="main-contents">

		<div class="header">
    		<c:if test="${ empty loginUser }">
        		<a href="login">ログイン</a>
        		<a href="signup">登録する</a>
    		</c:if>
    		<c:if test="${ not empty loginUser }">
        		<a href="./">ホーム</a>
        		<a href="setting">設定</a>
        		<a href="logout">ログアウト</a>
    		</c:if>
		</div>


		<c:if test="${ not empty loginUser }">
    		<div class="profile">
        		<div class="name"><h2><c:out value="${loginUser.name}" /></h2></div>
        		<div class="account">@<c:out value="${loginUser.account}" /></div>
        		<div class="description"><c:out value="${loginUser.description}" /></div>
    		</div>
		</c:if>


		<c:if test="${ not empty errorMessages }">
    		<div class="errorMessages">
        		<ul>
           			<c:forEach items="${errorMessages}" var="errorMessage">
               			<li><c:out value="${errorMessage}" />
           			</c:forEach>
        		</ul>
    		</div>
    		<c:remove var="errorMessages" scope="session" />
		</c:if>

		<div class="form-area">
        		<form action="edit" method="post">
        			<input type="hidden" name="id" value="${message.id}">
    	       		<br />
        	   		<textarea name="text" cols="100" rows="5" class="tweet-box"><c:out value="${message.text}" /></textarea>
           			<br />
           			<input type="submit" value="更新">（140文字まで）
        		</form>
		</div>

		<div class="copyright"> Copyright(c)Sone Hiroto</div>
        </div>

    </body>
</html>

WebContent/login.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>ログイン</title>
        <link href="./css/style.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="main-contents">

            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="errorMessage">
                            <li><c:out value="${errorMessage}" />
                        </c:forEach>
                    </ul>
                </div>
                <c:remove var="errorMessages" scope="session" />
            </c:if>

            <form action="login" method="post"><br />
                <label for="accountOrEmail">アカウント名かメールアドレス</label>
                <input name="accountOrEmail" id="accountOrEmail"/> <br />

                <label for="password">パスワード</label>
                <input name="password" type="password" id="password"/> <br />

                <input type="submit" value="ログイン" /> <br />
                <a href="./">戻る</a>
            </form>

            <div class="copyright"> Copyright(c)YourName</div>
        </div>
    </body>
</html>

WebContent/setting.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>${loginUser.account}の設定</title>
        <link href="css/style.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="main-contents">

            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="errorMessage">
                            <li><c:out value="${errorMessage}" />
                        </c:forEach>
                    </ul>
                </div>
                <c:remove var="errorMessages" scope="session" />
            </c:if>

            <form action="setting" method="post"><br />
                <input name="id" value="${user.id}" id="id" type="hidden"/>

                <label for="name">名前</label>
                <input name="name" value="${user.name}" id="name"/>（名前はあなたの公開プロフィールに表示されます）<br />

                <label for="account">アカウント名</label>
                <input name="account" value="${user.account}" /><br />

                <label for="password">パスワード</label>
                <input name="password" type="password" id="password"/> <br />

                <label for="email">メールアドレス</label>
                <input name="email" value="${user.email}" id="email"/> <br />

                <label for="description">説明</label>
                <textarea name="description" cols="35" rows="5" id="description"><c:out value="${user.description}" /></textarea> <br />

                <input type="submit" value="更新" /> <br />
                <a href="./">戻る</a>
            </form>

            <div class="copyright"> Copyright(c)Your Name</div>
        </div>
    </body>
</html>

WebContent/signup.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
	    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	    <title>ユーザー登録</title>
		<link href="./css/style.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="main-contents">

            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="errorMessage">
                            <li><c:out value="${errorMessage}" />
                        </c:forEach>
                    </ul>
                </div>
            </c:if>

            <form action="signup" method="post"><br />
                <label for="name">名前</label>
                <input name="name" id="name" />（名前はあなたの公開プロフィールに表示されます）<br />

                <label for="account">アカウント名</label>
                <input name="account" id="account" /> <br />

                <label for="password">パスワード</label>
                <input name="password" type="password" id="password" /> <br />

                <label for="email">メールアドレス</label>
                <input name="email" id="email" /> <br />

                <label for="description">説明</label>
                <textarea name="description" cols="35" rows="5" id="description"></textarea> <br />
                <input type="submit" value="登録" /> <br />
                <a href="./">戻る</a>
            </form>

            <div class="copyright">Copyright(c)Your Name</div>
        </div>
    </body>
</html>

WebContent/top.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>簡易Twitter</title>
        <link href="./css/style.css" rel="stylesheet" type="text/css">
    </head>

    <body>
	<div class="main-contents">

		<div class="header">
    		<c:if test="${ empty loginUser }">
        		<a href="login">ログイン</a>
        		<a href="signup">登録する</a>
    		</c:if>
    		<c:if test="${ not empty loginUser }">
        		<a href="./">ホーム</a>
        		<a href="setting">設定</a>
        		<a href="logout">ログアウト</a>
    		</c:if>
		</div>


		<c:if test="${ not empty loginUser }">
    		<div class="profile">
        		<div class="name"><h2><c:out value="${loginUser.name}" /></h2></div>
        		<div class="account">@<c:out value="${loginUser.account}" /></div>
        		<div class="description"><c:out value="${loginUser.description}" /></div>
    		</div>
		</c:if>


		<c:if test="${ not empty errorMessages }">
    		<div class="errorMessages">
        		<ul>
           			<c:forEach items="${errorMessages}" var="errorMessage">
               			<li><c:out value="${errorMessage}" />
           			</c:forEach>
        		</ul>
    		</div>
    		<c:remove var="errorMessages" scope="session" />
		</c:if>

		<div class="search">
			<form action="./" method="get">
				日付
				<input type="date" name="start" value="${start}">
				～
    			<input type="date" name="end" value="${end}">
    			<input type="submit" value="絞込">
    		</form>
    	</div>

		<div class="form-area">
    		<c:if test="${ isShowMessageForm }">
        		<form action="message" method="post">
           			いま、どうしてる？<br />
           			<textarea name="text" cols="100" rows="5" class="tweet-box"></textarea>
           			<br />
           			<input type="submit" value="つぶやく">（140文字まで）
        		</form>
    		</c:if>
		</div>


		<div class="messages">
    		<c:forEach items="${messages}" var="message">
        		<div class="message">
           			<div class="account-name">
               			<span class="account">
               				<a href="./?user_id=<c:out value="${message.userId}"/> ">
               					<c:out value="${message.account}" />
               				</a>
               			</span>
               			<span class="name"><c:out value="${message.name}" /></span>
           			</div>
           			<div class="text"></div>

           			<c:forEach var="s" items="${message.splitedText}">
           				<div><c:out value="${s}" /></div>
           			</c:forEach>

           			<div class="date"><fmt:formatDate value="${message.createdDate}" pattern="yyyy/MM/dd HH:mm:ss" /></div>


           			<div class="edit">
           			    <c:if test="${ isShowMessageForm }">
	           				<form action="edit" method="get">
	           					<input type="hidden" name="id" value="${message.id}">
	           						<c:if test="${message.userId == loginUser.id}">
           								<input type="submit" value="編集">
           							</c:if>
           					</form>
						</c:if>
           			</div>

           			<div class="deleteMessage">
           			    <c:if test="${ isShowMessageForm }">
	           				<form action="deleteMessage" method="post">
	           					<input type="hidden" name="id" value="${message.id}">
	           						<c:if test="${message.userId == loginUser.id}">
           								<input type="submit" value="削除">
           							</c:if>
           					</form>
						</c:if>
           			</div>

           			<div class="form-area">
    					<c:if test="${ isShowMessageForm }">
        					<form action="comment" method="post">
           						<input type="hidden" name="id" value="${message.id}">
           						<br />
           						<textarea name="text" cols="100" rows="5" class="tweet-box"></textarea>
           						<br />
           						<input type="submit" value="返信">（140文字まで）
        					</form>
    					</c:if>
					</div>


					<div class="comments">
    					<c:forEach items="${comments}" var="comment">
    						<c:if test="${message.id == comment.messageId}">
				        		<div class="comment">
    	       						<div class="account-name">
        	       						<span class="account">
               								<c:out value="${comment.account}" />
               							</span>
               							<span class="name"><c:out value="${comment.name}" /></span>
           							</div>
           							<div class="text"></div>

           							<c:forEach var="s" items="${comment.splitedText}">
           								<div><c:out value="${s}" /></div>
           							</c:forEach>

           							<div class="date"><fmt:formatDate value="${comment.createdDate}" pattern="yyyy/MM/dd HH:mm:ss" /></div>
					        	</div>
					        </c:if>
    					</c:forEach>
					</div>



        		</div>
    		</c:forEach>
		</div>


		<div class="copyright"> Copyright(c)Sone Hiroto</div>
        </div>

    </body>
</html>